const BASE = 'computedContainer'

export const ADD_COMPUTED_VALUE = `${BASE}/ADD_COMPUTED_VALUE`
export const UPDATE_COMPUTED_VALUE = `${BASE}/UPDATE_COMPUTED_VALUE`
export const DEL_COMPUTED_VALUE = `${BASE}/DEL_COMPUTED_VALUE`
